name: Package Extension
description: Package an extension into a tarball for release

inputs:
  extension-name:
    description: The name of the extension
    required: true
    type: string
  artifact-name:
    description: The name of the artifact
    required: false
    type: string

runs:
  using: "composite"

  steps:
    - name: Create tar
      if: ${{ inputs.artifact-name == '' }}
      run: tar -czf ${{ inputs.extension-name}}.tar.gz ./extensions/${{ inputs.extension-name}}
      shell: bash

    - name: Download optional artifact
      if: ${{ inputs.artifact-name != '' }}
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.extension-name }}

    - name: Create tar from artifact
      if: ${{ inputs.artifact-name != '' }}
      run: tar -czf ${{ inputs.extension-name }}.tar.gz ${{ inputs.extension-name }}
      shell: bash

    - name: Upload extension tar
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.extension-name }}.tar.gz
        path: ${{ inputs.extension-name }}.tar.gz
