name: Extension Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  simple-extension-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      # Expose matched filters as 'changes' output variable
      changes: ${{ steps.changes.outputs.changes }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            reaper: extensions/reaper/**
            integration-session-manager: extensions/integration-session-manager/**

  simple-extensions:
    needs: [simple-extension-changes]
    # https://github.com/dorny/paths-filter/issues/66#issuecomment-778267385
    if: ${{ needs.simple-extension-changes.outputs.changes != '[]' && needs.simple-extension-changes.outputs.changes != '' }}
    strategy:
      # Do not fail fast so all extensions are processed
      fail-fast: false
      matrix:
        # Parse JSON containing names of all filters matching any of changed extensions
        # e.g. ['reaper'] if the reaper extension dir changed
        extension: ${{ fromJSON(needs.simple-extension-changes.outputs.changes) }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/package-extension
        with:
          extension-name: ${{ matrix.extension }}

      - uses: ./.github/actions/release-extension
        id: release_extension
        with:
          extension-name: ${{ matrix.extension }}

  complex-extension-changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      publisher-command-center: ${{ steps.changes.outputs.publisher-command-center }}

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            publisher-command-center: extensions/publisher-command-center/**

  publisher-command-center:
    runs-on: ubuntu-latest
    needs: [complex-extension-changes]
    if: ${{ needs.complex-extension-changes.outputs.publisher-command-center == 'true' }}

    steps:
      - run: echo "Publisher Command Center"

  fetch-releases:
    runs-on: ubuntu-latest
    needs: [simple-extensions, publisher-command-center]
    if: ${{ always() }}
    outputs:
      releases: ${{ steps.fetch-releases.outputs.releases }}

    steps:
      - name: Download GitHub release data
        uses: actions/download-artifact@v4
        with:
          pattern: release-*.json
          path: releases
          merge-multiple: true

      - name: Fetch releases
        id: fetch-releases
        run: echo "releases=$(cat releases/*.json | jq -c --slurp .)" >> "$GITHUB_OUTPUT"

      - run: echo '${{ steps.fetch-releases.outputs.releases }}'

  update-extension-list:
    runs-on: ubuntu-latest
    needs: [fetch-releases]
    env:
      RELEASES: ${{ needs.fetch-releases.outputs.releases }}

    steps:
      - run: echo '${{ env.RELEASES }}'

      # - uses: actions/checkout@v4

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: "lts/*"
      #     cache: "npm"
      #     cache-dependency-path: scripts/package-lock.json

      # - run: npm ci
      #   working-directory: ./scripts

      # - run: npm run update-extension-list
      #   working-directory: ./scripts

      # - run: cat extensions.json
