name: Publisher Commander Center Extension

on:
  pull_request:
    paths:
      - 'extensions/publisher-command-center/**'
  push:
    branches:
      - 'main'
    paths:
      - 'extensions/publisher-command-center/**'

env:
  EXTENSION_NAME: publisher-command-center

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extensions/${{ env.EXTENSION_NAME }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: extensions/${{ env.EXTENSION_NAME }}/package-lock.json

      - run: npm ci
      - run: npm run build

      - name: Upload built extension
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXTENSION_NAME }}
          path: |
            extensions/${{ env.EXTENSION_NAME }}/dist/
            extensions/${{ env.EXTENSION_NAME }}/requirements.txt
            extensions/${{ env.EXTENSION_NAME }}/app.py
            extensions/${{ env.EXTENSION_NAME }}/manifest.json
            extensions/${{ env.EXTENSION_NAME }}/connect-extension.toml

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
            name: ${{ env.EXTENSION_NAME}}
            path: ${{ env.EXTENSION_NAME }}

      - name: Create tar
        run: tar -czf $EXTENSION_NAME.tar.gz $EXTENSION_NAME

      - name: Upload extension tar
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXTENSION_NAME }}.tar.gz
          path: ${{ env.EXTENSION_NAME }}.tar.gz

  should_release:
    # if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extensions/${{ env.EXTENSION_NAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Get manifest
        id: get_manifest
        run: echo "EXTENSION_MANIFEST=$(jq -c . < manifest.json)" >> "$GITHUB_ENV"

      - run: echo "$EXTENSION_MANIFEST"

      # - run: echo '${{ fromJson(env.PACKAGE_JSON).version }}'

      # - name: Use environment variable
      #   run: echo "The value of manifest is ${{ steps.get_manifest.outputs.manifest }}"
          
      # - name: Access extension attributes
      #   run: echo "The version is ${{ fromJSON(steps.get_manifest.outputs.manifest).version }}"

  release:
    if: github.event_name == 'push' && github.ref_name == 'main'
    needs: [should_release, package]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      extension_url: ${{ steps.get_extension_url.outputs.extension_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.EXTENSION_NAME }}.tar.gz
  
      - name: Release
        run: gh release create $EXTENSION_NAME@v0.0.4 --title "$EXTENSION_NAME v0.0.4" $EXTENSION_NAME.tar.gz

      - name: Get extension URL
        id: get_extension_url
        run: |
          url=$(gh release view --json assets --jq '.assets[0].url')
          echo "extension_url=$url" >> "$GITHUB_OUTPUT"
