name: Reaper Extension

on:
  pull_request:
    paths:
      - 'extensions/reaper/**'
  workflow_dispatch:

env:
  EXTENSION_NAME: reaper

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create tar
        working-directory: ./extensions
        run: tar -czf $EXTENSION_NAME.tar.gz $EXTENSION_NAME

      - name: Upload extension tar
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXTENSION_NAME }}.tar.gz
          path: extensions/${{ env.EXTENSION_NAME }}.tar.gz

  should-release:
    uses: ./.github/workflows/should-release.yml
    with:
      extension-name: reaper
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  release:
    if: needs.should-release.outputs.should-release == 'true'
    uses: ./.github/workflows/release.yml
    needs: [should-release]
    with:
      extension-name: reaper
      version: ${{ needs.should-release.outputs.version }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
