name: Check if extension should be released

on:
  workflow_call:
    inputs:
      extension-name:
        description: "The name of the extension"
        required: true
        type: string
    outputs:
      should-release:
        description: "Whether the extension should be released"
        value: ${{ jobs.should_release.outputs.should-release }}
      version:
        description: "The version of the extension to be released"
        value: ${{ jobs.should_release.outputs.version }}

jobs:
  should_release:
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extensions/${{ inputs.extension-name }}
    outputs:
      should-release: ${{ steps.should_release.outputs.should_release }}
      version: ${{ steps.should_release.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: npm install -g semver

      - name: Get extension manifest
        run: echo "EXTENSION_MANIFEST=$(jq -c . < manifest.json)" >> "$GITHUB_ENV"

      - name: Get manifest extension version
        run: echo "MANIFEST_VERSION=$(echo $EXTENSION_MANIFEST | jq -r '.extension.version')" >> "$GITHUB_ENV"

      - name: Get last released version
        run: |
          LAST_RELEASED_VERSION=$(semver -c $(gh release view --json tagName --jq '.tagName'))
          echo "LAST_RELEASED_VERSION=$LAST_RELEASED_VERSION" >> "$GITHUB_ENV"

      - name: Check if manifest has newer version
        id: should_release
        run: |
          echo "The last released version is '$LAST_RELEASED_VERSION' and the manifest version is '$MANIFEST_VERSION'"
          HIGHER_VERSION=$(semver "$MANIFEST_VERSION" "$LAST_RELEASED_VERSION" | tail -n 1)
            if [ "$MANIFEST_VERSION" = "$HIGHER_VERSION" ] && [ "$MANIFEST_VERSION" != "$LAST_RELEASED_VERSION" ]; then
            echo "Should release: the manifest version is higher than the last released version"
            echo "should_release=true" >> "$GITHUB_OUTPUT"
            echo "version=$MANIFEST_VERSION" >> "$GITHUB_OUTPUT"
          else
            echo "Should not release: the manifest version is not higher than the last released version"
            echo "should_release=false" >> "$GITHUB_OUTPUT"
          fi
